### ISSUE TITLE
DMRcate Seems To Have Issues Getting Around an HPC/Proxy

### ISSUE THREAD

**Issue by yr542** [rcavalcante/DMRcate#1]
**My goal:** I am trying to use DMRcate to find some differentially methylated regions.

_Issue Description:_ When I run the following code it does not give the expected result even when I try localHub = TRUE or localHub = FALSE it still gives and error:

**_Attempt 1:_** 

```r
# Converting DMR list
results.ranges <- extractRanges(dmrcoutput, genome = "hg19")
```

The error is below:

> Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead
>
> Using 'localHub=TRUE'
>  If offline, please also see BiocManager vignette section on offline use
>
> snapshotDate(): 2023-01-30
>
> Error: File not previously downloaded.
>  Run with 'localHub=FALSE'
> Traceback:
>
> 1. extractRanges(dmrcoutput, genome = "hg19")
> 2. eh[["EH3132"]]
> 3. eh[["EH3132"]]
> 4. .local(x, i, j = j, ...)
> 5. stop("File not previously downloaded.\n", "  Run with 'localHub=FALSE'", 
>  .     call. = FALSE)

**_Attempt 2_** (with localHub = TRUE):

```r
# Converting DMR list
results.ranges <- extractRanges(dmrcoutput, genome = "hg19", localHub=TRUE)
```

It gives the error:

> Error in extractRanges(dmrcoutput, genome = "hg19", localHub = TRUE): unused argument (localHub = TRUE)
> Traceback:

**_Attempt 3_** (with localHub = FALSE):

```r
# Converting DMR list
results.ranges <- extractRanges(dmrcoutput, genome = "hg19", localHub=FALSE)
```

It gives the error:

> Error in extractRanges(dmrcoutput, genome = "hg19", localHub = FALSE): unused argument (localHub = FALSE)
> Traceback:

This seems to be associated with what I believe might be an issue with the DMRcate software itself. Is there a way around this?

**Comment by rcavalcante** [comment]
Hi,

I am not the actual maintainer of this package, this is a fork of the package for personal use and is not maintained. Apologies, but please contact the DMRcate maintainers via support.bioconductor.org or their GitHub repo.

Thanks,
Raymond

**Comment by yr542** [comment]
Do you perchance you where their Github repo is? I could only find yours?

**Comment by rcavalcante** [comment]
It seems you're right, as I can't find a GitHub repo either. I must have downloaded the source and made the repo that way. Nevertheless, I think support.bioconductor.org is your best bet; just make sure to tag the question with DMRcate so that the right people are theoretically notified.

Sorry about that.

**Comment by yr542** [comment]
Thank you. If you prefer I can take this post down?

**Comment by rcavalcante** [comment]
Thank you, but no need, I closed the issue, and it may be relevant if someone else happens upon this repo again.
